config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :monetary_accounts
  root 'home#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :bunqauth
  resources :monetary_accounts, only: [:index, :create]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  get 'bunq', to: 'bunqauth#redirect', as: 'bunq'
  get 'bunqlogin', to: 'bunqauth#new', as: 'bunqlogin'
end

app/models/monetary_account.rb
class MonetaryAccount < ApplicationRecord
  belongs_to :user
  has_many :transactions

  validates :account_id, presence: true, uniqueness: true  
end

app/controllers/monetary_accounts_controller.rb
class MonetaryAccountsController < ApplicationController
  before_action :set_monetary_account, only: [:show, :edit, :update, :destroy]

  def index
    @monetary_account = MonetaryAccount.new
    @available_accounts = fetch
    @available_accounts.each do |account| 
      monetary_account = MonetaryAccount.find_by_account_id(account[:account_id])
      if !monetary_account.nil?
          account[:user_id] = monetary_account.user_id
          account[:id] = monetary_account.id
      end
    end
  end

  def show
  end

  def new
    @monetary_account = MonetaryAccount.new
  end

  def edit
  end

  def create
    @monetary_account = MonetaryAccount.new(monetary_account_params)
    

    respond_to do |format|
      if @monetary_account.save
        format.html { redirect_to @monetary_account, notice: 'Monetary account was successfully created.' }
        format.json { render :show, status: :created, location: @monetary_account }
      else
        format.html { render :new }
        format.json { render json: @monetary_account.errors, status: :unprocessable_entity }
        puts @monetary_account.errors.full_messages
      end
    end
  end

  private

  def fetch
    Bunq.client.me_as_user.monetary_accounts.index.each_with_object([]) do |monetary_account, arr|
      account = {account_id: monetary_account['MonetaryAccountBank']['id'],
                name: monetary_account['MonetaryAccountBank']['description'],
                balance: monetary_account['MonetaryAccountBank']['balance']['value']
              }
      arr << account
    end
  end

  def set_monetary_account
    @monetary_account = MonetaryAccount.find(params[:id])
  end

  def monetary_account_params
    params.require(:monetary_account).permit(:account_id, :user_id, :name)
  end
end

app/helpers/monetary_accounts_helper.rb
module MonetaryAccountsHelper
end

app/views/monetary_accounts/_form.html.erb
<%= form_with(model: monetary_account, local: true) do |form| %>
  <% if monetary_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monetary_account.errors.count, "error") %> prohibited this monetary_account from being saved:</h2>
      <ul>
      <% monetary_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.number_field :account_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/monetary_accounts/edit.html.erb
<h1>Editing Monetary Account</h1>

<%= render 'form', monetary_account: @monetary_account %>

<%= link_to 'Show', @monetary_account %> |
<%= link_to 'Back', monetary_accounts_path %>

app/views/monetary_accounts/index.html.erb
<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %>
  <p id="notice"><%= notice %></p>
  <h1>Monetary Accounts</h1>

  <table>
    <thead>
      <tr>
        <th>Bunq Id</th>
        <th>Name</th>
        <th>Balance</th>
        <th>User</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @available_accounts.each do |available_account| %>
        <tr>
          <% if !available_account[:id].nil? %>
            <td><%= available_account[:account_id] %></td>
            <td><%= available_account[:name] %></td>
            <td><%= available_account[:balance] %></td>
            <td><%= available_account[:user_id] %></td>
          <% else %>
            <%= form_for @monetary_account, url: {action: "create"} do |f| %>
              <td><%= f.number_field :account_id, value: available_account[:account_id] %></td>
              <td><%= f.text_field :name, value: available_account[:name] %></td>
              <td><%= available_account[:balance] %></td>
              <td><%= f.number_field :user_id, value: current_user[:id] %></td>
              <td><%= f.submit "Create" %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  

<% else %>
  <%= link_to "Sign Up", signup_path %> or 
  <%= link_to "Log In", login_path %>
<% end %>

app/views/monetary_accounts/new.html.erb
<h1>New Monetary Account</h1>


<%= link_to 'Back', monetary_accounts_path %>

app/views/monetary_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @monetary_account.account_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @monetary_account.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @monetary_account.name %>
</p>

<%= link_to 'Edit', edit_monetary_account_path(@monetary_account) %> |
<%= link_to 'Back', monetary_accounts_path %>